blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¬ Discussions"
    url: "https://github.com/iHost-Open-Source-Project/hassio-ihost-addon/discussions"
    about: "For general Q&A and ideas, please use Discussions."
